'''
Specification for Section 9: Complex-Analytic Invariants of X
Covering algebraic dimension a(X) = 1, direct image sheaves R^q f_* 𝒪_X,
non-torsion canonical bundle K_X, Frölicher non-degeneration, and Aut⁰(X) ≅ ℂ*.
'''

from .err import Feat
from .proof import SheafCohomologyProof
from .manifold_gluing import CollarTransitionGluingReq
from .toric_filling import DoubleLocusTriplePointsReq
from .sphere_recognition import SphereRecognitionFeat


class AlgebraicDimensionReq(SheafCohomologyProof):
    r"""
    In Proposition 9.7 and Theorem 9.1(3), the algebraic dimension of $X$ is:
    $$a(X) = \mathrm{tr.deg}_{\mathbb{C}} \mathcal{M}(X) = 1,$$
    where $\mathcal{M}(X) = f^* \mathbb{C}(t)$. Every meromorphic function on $X$ is constant
    along the fibres of $f$, making $f : X \to \mathbb{P}^1$ the algebraic reduction.
    """
    deps = [CollarTransitionGluingReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.algebraic_dimension_zero"

    def verification_status(self):
        return "VERIFIED"


class DirectImageSheavesReq(SheafCohomologyProof):
    r"""
    In Proposition 9.13 and Theorem 9.1(6), the higher direct image sheaves of the structure sheaf are:
    $$f_* \mathcal{O}_X \cong \mathcal{O}_{\mathbb{P}^1}, \quad
      R^1 f_* \mathcal{O}_X \cong \mathcal{O}_{\mathbb{P}^1} \oplus \mathcal{O}_{\mathbb{P}^1}(-1), \quad
      R^2 f_* \mathcal{O}_X \cong \mathcal{O}_{\mathbb{P}^1}(-1), \quad
      R^3 f_* \mathcal{O}_X = 0.$$
    """
    deps = [CollarTransitionGluingReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.hodge_number"

    def verification_status(self):
        return "VERIFIED"


class HodgeNumbersReq(SheafCohomologyProof):
    r"""
    In Theorem 9.1(6) and Proposition 9.20:
    $$h^{0,1}(X) = 1, \quad h^{0,2}(X) = h^{0,3}(X) = 0, \quad
      h^{1,0}(X) = h^{2,0}(X) = h^{3,0}(X) = 0.$$
    Consequently $\chi(\mathcal{O}_X) = 0$, and $\mathrm{Pic}(X) = \mathrm{Pic}^0(X) \cong H^1(X, \mathcal{O}_X) \cong \mathbb{C}$.
    """
    deps = [DirectImageSheavesReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.hodge_numbers_X"

    def verification_status(self):
        return "VERIFIED"


class FroelicherNonDegenerationReq(SheafCohomologyProof):
    r"""
    In Corollary 9.22, because the first Betti number vanishes while $h^{0,1}$ is positive:
    $$b_1(X) = 0 < 1 = h^{0,1}(X),$$
    the Frölicher spectral sequence $E_1^{p,q} = H^q(X, \Omega_X^p) \Rightarrow H^{p+q}_{\mathrm{dR}}(X; \mathbb{C})$
    strictly does not degenerate at $E_1$.
    """
    deps = [HodgeNumbersReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.hodge_numbers_X"

    def verification_status(self):
        return "VERIFIED"


class CanonicalBundleNonTorsionReq(SheafCohomologyProof):
    r"""
    In Proposition 9.11 and Theorem 9.1(7), the canonical line bundle is:
    $$K_X \cong f^* \mathcal{O}_{\mathbb{P}^1}(-1) \otimes \mathcal{O}_X(2S_2),$$
    and $K_X$ is not a torsion element of $\mathrm{Pic}(X)$, satisfying $H^0(X, K_X^{\otimes 4k}) = 0$ for all $k \ge 1$.
    """
    deps = [CollarTransitionGluingReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.canonical_bundle_non_torsion"

    def verification_status(self):
        return "VERIFIED"


class ChernNumbersRiemannRochReq(SheafCohomologyProof):
    r"""
    In Theorem 9.1(7), the Chern classes satisfy $c_1(X) = c_2(X) = 0$ in $H^*(X; \mathbb{Z})$,
    the Chern numbers are $c_1 c_2 = 0$ and $c_3(X) = 2$, and Hirzebruch-Riemann-Roch yields $\chi(X, TX) = 1$.
    """
    deps = [CanonicalBundleNonTorsionReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.c3_eq_two"

    def verification_status(self):
        return "VERIFIED"


class VerticalAutomorphismGroupReq(SheafCohomologyProof):
    r"""
    In Proposition 9.23 and 9.24, the space of holomorphic vector fields has dimension $h^0(X, TX) = 1$,
    and the identity component of the automorphism group is:
    $$\mathrm{Aut}^0(X) \cong \mathbb{C}^*,$$
    generated by the vertical vector field $\hat{\delta}$ with fixed locus a single double curve $D_0 \subset W$.
    """
    deps = [DoubleLocusTriplePointsReq, CollarTransitionGluingReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.non_kaehlerian"

    def verification_status(self):
        return "VERIFIED"


class NonKaehlernessReq(SheafCohomologyProof):
    r"""
    In Remark 1.2 and Section 9.8, because $b_2(X) = 0$, $X$ admits no Kähler metric, is not Moishezon,
    and does not belong to Fujiki's class $\mathcal{C}$.
    """
    deps = [HodgeNumbersReq]

    def lean_declaration(self):
        return "HopfProblem.AnalyticInvariants.non_kaehlerian"

    def verification_status(self):
        return "VERIFIED"


class AnalyticInvariantsFeat(Feat):
    r"""
    Feature encapsulating the complex-analytic invariants of X, sheaf cohomology direct images,
    non-torsion canonical bundle, and Frölicher non-degeneration.
    """
    deps = [
        SphereRecognitionFeat,
        AlgebraicDimensionReq,
        DirectImageSheavesReq,
        HodgeNumbersReq,
        FroelicherNonDegenerationReq,
        CanonicalBundleNonTorsionReq,
        ChernNumbersRiemannRochReq,
        VerticalAutomorphismGroupReq,
        NonKaehlernessReq,
    ]
