'''
Specification for Section 2: Lattice and Monodromy Data
Covering the rank-4 lattice V, dual lattice Λ, triangle representation Δ(3, 4, ∞) → SL₄(ℤ),
unipotent cusp monodromy, toric vanishing sublattice, and invariant alternating form.
'''

from .err import Feat
from .proof import LatticeMonodromyProof


class LatticeBasisReq(LatticeMonodromyProof):
    r"""
    In Section 2.1 of the paper, the lattice $V \cong \mathbb{Z}^4$ has basis $(\gamma, u, w, \delta)$,
    and its dual lattice $\Lambda = V^* = \mathrm{Hom}(V, \mathbb{Z})$ has dual basis
    $(\hat{\gamma}, \hat{u}, \hat{w}, \hat{\delta})$ with pairings $\langle \hat{\alpha}, \beta \rangle = \delta_{\alpha,\beta}$.
    The system must formalize `V` and `Lambda` as free $\mathbb{Z}$-modules of rank 4 with canonical dual pairings.
    """
    deps = []

    def lean_declaration(self):
        return "HopfProblem.Lattice.V"

    def verification_status(self):
        return "VERIFIED"


class MonodromyGeneratorsReq(LatticeMonodromyProof):
    r"""
    In Definition 2.1 and Lemma 2.2, the automorphisms $T_1, T_2 \in \mathrm{Aut}(V)$ are given by:
    $$T_1 = \begin{pmatrix} 1 & 0 & -6 & 2 \\ 0 & -1 & 1 & 1 \\ 0 & -1 & 0 & 1 \\ 0 & 0 & 0 & 1 \end{pmatrix}, \quad
      T_2 = \begin{pmatrix} 1 & 6 & 0 & -3 \\ 0 & 0 & -1 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix}.$$
    The system must formalize $T_1, T_2$, prove $\det(T_1) = \det(T_2) = 1$, and verify orders:
    $T_1^3 = I$ and $T_2^4 = I$.
    """
    deps = [LatticeBasisReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.T1_cube"

    def verification_status(self):
        return "VERIFIED"


class UnipotentCuspMonodromyReq(LatticeMonodromyProof):
    r"""
    In Definition 2.1 and Lemma 2.2(iii), the parabolic cusp monodromy is $T_0 := (T_1 T_2)^{-1} = I + N$,
    where the nilpotent matrix $N = T_0 - I$ satisfies:
    $$N^2 = 0, \quad N\gamma = 0, \quad Nu = 0, \quad Nw = -u, \quad N\delta = \gamma.$$
    The system must formalize $T_0$ and $N$, proving $N^2 = 0$ and Jordan rank 2.
    """
    deps = [MonodromyGeneratorsReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.T0_unipotent"

    def verification_status(self):
        return "VERIFIED"


class DualMonodromyMatricesReq(LatticeMonodromyProof):
    r"""
    In Definition 2.3 and Lemma 2.4, the dual representation on $\Lambda$ is given by $A_j := (T_j^{-1})^t$
    for $j \in \{1, 2\}$, and $M_0 := (T_0^{-1})^t = I - N^t$.
    The system must formalize the anti-homomorphism $T \mapsto (T^{-1})^t$ and verify $M_0 = (T_0^{-1})^t$.
    """
    deps = [MonodromyGeneratorsReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.A1"

    def verification_status(self):
        return "VERIFIED"


class ToricSublatticeReq(LatticeMonodromyProof):
    r"""
    In Definition 2.5 and Lemma 2.6, the toric vanishing sublattice is:
    $$\Lambda_{\mathrm{tor}} := \ker(M_0 - I) = \mathrm{im}(M_0 - I) = \langle \hat{w}, \hat{\delta} \rangle \subset \Lambda,$$
    and the quotient $\bar{\Lambda} := \Lambda / \Lambda_{\mathrm{tor}} \cong \mathbb{Z}^2$ has basis $(\bar{\hat{\gamma}}, \bar{\hat{u}})$.
    The operator $M_0 - I$ induces a unimodular $\mathbb{Z}$-linear isomorphism:
    $$B_0 : \bar{\Lambda} \xrightarrow{\sim} \Lambda_{\mathrm{tor}}, \quad \bar{\hat{\gamma}} \mapsto -\hat{\delta}, \quad \bar{\hat{u}} \mapsto \hat{w}.$$
    The system must formalize $\Lambda_{\mathrm{tor}}$, $\bar{\Lambda}$, and the isomorphism $B_0$.
    """
    deps = [UnipotentCuspMonodromyReq, DualMonodromyMatricesReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.LambdaTor"

    def verification_status(self):
        return "VERIFIED"


class MonodromyInvariantsReq(LatticeMonodromyProof):
    r"""
    In Lemma 2.7, under the group $G = \langle T_1, T_2 \rangle$:
    1. The invariant submodule $V^G = \mathbb{Q}\gamma \cap V = \mathbb{Z}\gamma$ is of rank 1.
    2. The coinvariant quotient of $\Lambda$ is $\Lambda / \ker\gamma \cong \mathbb{Z}$, detected by $\gamma$ alone.
    3. The vector $\varepsilon := \hat{\gamma} + 2\hat{u} - 4\hat{w}$ is fixed by $A_1$.
    4. The vector $\varepsilon' := \hat{\gamma} + 3\hat{u} - 3\hat{w}$ is fixed by $A_2$.
    The system must formalize and machine-check these invariant vectors and coinvariant projections.
    """
    deps = [MonodromyGeneratorsReq, DualMonodromyMatricesReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.A1_fixes_eps"

    def verification_status(self):
        return "VERIFIED"


class InvariantAlternatingFormReq(LatticeMonodromyProof):
    r"""
    In Lemma 2.8, the group of $G$-invariant alternating bilinear forms on $V$ is infinite cyclic,
    generated by $Q_0$ where:
    $$Q_0(\gamma, u) = 0, \quad Q_0(\gamma, w) = 0, \quad Q_0(\gamma, \delta) = 1, \quad
      Q_0(u, w) = 6, \quad Q_0(u, \delta) = 0, \quad Q_0(w, \delta) = 0.$$
    The system must formalize $Q_0 \in \bigwedge^2 \Lambda$ and prove $T_j^t Q_0 T_j = Q_0$ for $j \in \{1, 2\}$.
    """
    deps = [MonodromyGeneratorsReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.Q0_invariant_T1"

    def verification_status(self):
        return "VERIFIED"


class TriangleGroupOrbifoldReq(LatticeMonodromyProof):
    r"""
    In Proposition 2.11 and Definition 2.15, the triangle group
    $\Delta = \Delta(3, 4, \infty) = \langle g_1, g_2 \mid g_1^3 = g_2^4 = 1 \rangle \subset \mathrm{PSL}_2(\mathbb{R})$
    acts on the upper half plane $\mathfrak{h}_z$ uniformising the orbifold $B = \mathbb{P}^1$ with orbifold points
    $p_1 = 0$ (order 3), $p_2 = 1$ (order 4), and cusp $p_0 = \infty$.
    The representation $\rho_V : \Delta \to \mathrm{SL}(V)$ maps $g_j \mapsto T_j$ and $g_0 \mapsto T_0$.
    """
    deps = [MonodromyGeneratorsReq]

    def lean_declaration(self):
        return "HopfProblem.Lattice.monodromy_relation"

    def verification_status(self):
        return "VERIFIED"


class LatticeMonodromyFeat(Feat):
    r"""
    Feature encapsulating the $\mathrm{SL}_4(\mathbb{Z})$ lattice monodromy representation,
    distinguished sublattices, and triangle group uniformisation data of Section 2.
    """
    deps = [
        LatticeBasisReq,
        MonodromyGeneratorsReq,
        UnipotentCuspMonodromyReq,
        DualMonodromyMatricesReq,
        ToricSublatticeReq,
        MonodromyInvariantsReq,
        InvariantAlternatingFormReq,
        TriangleGroupOrbifoldReq,
    ]
