'''
Specification for Section 3: The Period Family over the Thrice-Punctured Sphere
Covering the modular period map Π(z), uniformising function τ, torsor μ, period β,
indefinite Hodge signature (1, 1), and smooth family of complex 2-tori.
'''

from .err import Feat
from .proof import ModularPeriodProof
from .lattice_monodromy import MonodromyGeneratorsReq, TriangleGroupOrbifoldReq


class PeriodMatrixReq(ModularPeriodProof):
    r"""
    In Definition 3.3 and Theorem 3.4, the period matrix $\Pi(z) \in M_{2 \times 4}(\mathbb{C})$
    over $z \in \mathfrak{h}_z$ is given in the dual basis $(\hat{\gamma}, \hat{u}, \hat{w}, \hat{\delta})$ by:
    $$\Pi(z) = \begin{pmatrix} 6\mu(z) & \tau(z) & 1 & 0 \\ \beta(z) & \mu(z) & 0 & 1 \end{pmatrix}.$$
    The system must formalize $\Pi(z)$ as a $\mathbb{C}$-linear map $\Lambda \otimes \mathbb{R} \to \mathbb{C}^2$.
    """
    deps = [MonodromyGeneratorsReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.periodMatrix"

    def verification_status(self):
        return "VERIFIED"


class UniformisingTauReq(ModularPeriodProof):
    r"""
    In Proposition 3.6 and Lemma 3.5, the holomorphic function $\tau : \mathfrak{h}_z \to \mathfrak{h}$
    satisfies the modular equation:
    $$j(\tau(z)) = 1728\, (t \circ \pi)(z)$$
    identifying $\tau$ with the modular uniformisation of $B = \mathbb{P}^1$ punctured at $\{p_0, p_1, p_2\}$.
    """
    deps = [TriangleGroupOrbifoldReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.UpperHalfPlane"

    def verification_status(self):
        return "VERIFIED"


class MuTorsorReq(ModularPeriodProof):
    r"""
    In Proposition 3.11 and Lemma 3.10, the holomorphic function $\mu : \mathfrak{h}_z \to \mathbb{C}$
    satisfies the 1-cocycle automorphy relation under $\Delta$, defining a torsor under the line bundle:
    $$\mathcal{L} \cong \mathcal{O}_{\mathbb{P}^1}(-p_0) \cong \mathcal{O}_{\mathbb{P}^1}(-1),$$
    with $H^0(\mathbb{P}^1, \mathcal{L}) = H^1(\mathbb{P}^1, \mathcal{L}) = 0$.
    """
    deps = [TriangleGroupOrbifoldReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.PeriodData"

    def verification_status(self):
        return "VERIFIED"


class BetaPeriodReq(ModularPeriodProof):
    r"""
    In Proposition 3.13 and Lemma 3.14, the holomorphic function $\beta : \mathfrak{h}_z \to \mathbb{C}$
    satisfies the non-degeneracy condition for all $z \in \mathfrak{h}_z$:
    $$\Im\tau(z) \, \Im\beta(z) - 6\, (\Im\mu(z))^2 > 0,$$
    ensuring that the four column vectors of $\Pi(z)$ are $\mathbb{R}$-linearly independent in $\mathbb{C}^2 \cong \mathbb{R}^4$.
    """
    deps = [UniformisingTauReq, MuTorsorReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.PeriodData"

    def verification_status(self):
        return "VERIFIED"


class ModularEquivarianceReq(ModularPeriodProof):
    r"""
    In Proposition 3.16 and 3.19, the period matrix satisfies the modular equivariance:
    $$\Pi(g z) = J_g(z) \, \Pi(z) \, M_g^{-1} \quad \text{for all } g \in \Delta,$$
    where $J_g(z) \in \mathrm{GL}_2(\mathbb{C})$ is the holomorphic automorphy matrix and $M_g = \rho_V(g)^t$.
    """
    deps = [PeriodMatrixReq, UniformisingTauReq, MuTorsorReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.modular_equivariance"

    def verification_status(self):
        return "VERIFIED"


class IndefiniteHodgeSignatureReq(ModularPeriodProof):
    r"""
    In Lemma 3.14 and Lemma 9.4, the Hodge form $H(z)$ on the fibre torus $F_z = \mathbb{C}^2 / \Pi(z)\Lambda$
    has signature $(1, 1)$, strictly indefinite.
    Consequently, the very general fibre carries no positive line bundle, has algebraic dimension $a(F) = 0$,
    and has Néron-Severi group $\mathrm{NS}(F) \cong \mathbb{Z}\eta$ generated by a single indefinite class $\eta$.
    """
    deps = [PeriodMatrixReq, BetaPeriodReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.indefinite_hodge_signature"

    def verification_status(self):
        return "VERIFIED"


class SmoothTorusFamilyReq(ModularPeriodProof):
    r"""
    In Theorem 3.4, the quotient:
    $$\mathcal{J} := (\mathfrak{h}_z \times \mathbb{C}^2) / (\Delta \ltimes \Lambda) \to B^\circ$$
    is a holomorphic submersion whose fibres over $B^\circ = \mathbb{P}^1 \setminus \{p_0, p_1, p_2\}$
    are smooth complex 2-tori.
    """
    deps = [ModularEquivarianceReq, IndefiniteHodgeSignatureReq]

    def lean_declaration(self):
        return "HopfProblem.PeriodFamily.smooth_torus_family_exists"

    def verification_status(self):
        return "VERIFIED"


class PeriodFamilyFeat(Feat):
    r"""
    Feature encapsulating the modular period family, uniformising functions,
    indefinite Hodge signature, and torus fibration over the thrice-punctured sphere.
    """
    deps = [
        PeriodMatrixReq,
        UniformisingTauReq,
        MuTorsorReq,
        BetaPeriodReq,
        ModularEquivarianceReq,
        IndefiniteHodgeSignatureReq,
        SmoothTorusFamilyReq,
    ]
